name: challenge
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_svg:
  flutter_mobx: ^1.1.0

dev_dependencies:
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/logo.png
    - assets/img/arrow.png
    - assets/img/banner.png
    - assets/img/backpack.png
    - assets/img/item.png
    - assets/img/icon_arrow.png
    - assets/img/icon_up.png
