name: challenge
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_svg:
  flutter_mobx: 1.1.0+1
  badges: ^1.1.1

dev_dependencies:
  mobx_codegen:
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/NeusaNextStd-Light.otf
          weight: 300
        - asset: assets/fonts/NeusaNextStd-Bold.otf
          weight: 400
        - asset: assets/fonts/NeusaNextStd-Medium.otf
          weight: 500
        - asset: assets/fonts/NeusaNextStd-Regular.otf
          weight: 700

  assets:
    - assets/img/logo.png
    - assets/img/arrow.png
    - assets/img/banner.png
    - assets/img/backpack.png
    - assets/img/item.png
    - assets/img/icon_order.png
    - assets/img/icon_arrow.png
    - assets/img/icon_up.png
    - assets/img/seeall.png
    - assets/img/shoes.png
    - assets/img/apparel.png
    - assets/img/beauty.png
